POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/54563441-6d1d-4c0d-94df-884c664cf28c/attendees
Content-Type: application/json

{
  "name": "Luis Felipe Salvarani",
  "email": "felipe_salvarani2@hotmail.com"
}

###

GET http://localhost:3333/events/54563441-6d1d-4c0d-94df-884c664cf28c